[K/N][tests] Mute failing lldb tests until KT-84923 is fixed
For some reason, the stepping tests for K/N started failing sporadically
on the CI, because lldb can't attach to the process:
```
error: process exited with status -1 (attach failed (attached to
process, but could not pause execution; attach failed))
```

Until the problem is investigated and fixed, the tests need to be muted.
To be on the safe side, all tests running lldb should be muted.

This commit does this in a soft way: if lldb exits with non-zero exit
code (like it happens when this problem occurs), the test is skipped.
If not, it proceeds to the next checks, including the output checker.
This way, the test will still be able to catch some problems, and a
successful status would mean that the test passed.